# Generated by Django 4.2.4 on 2023-08-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoleInOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('point', models.IntegerField()),
                ('club', models.CharField(max_length=30)),
            ],
        ),
    ]
