# Generated by Django 4.2.4 on 2023-08-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holes', '0002_holeinone_author_alter_holeinone_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holeinone',
            name='club',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='holeinone',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
