# Generated by Django 4.2.4 on 2023-08-07 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birth',
            field=models.DateField(blank=True, default=datetime.date(1970, 1, 1), null=True),
        ),
    ]
